name: Deploy
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages
  # Also trigger on page_build, as well as release created events
  page_build:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sudo apt-get install -y python3-setuptools
        pip3 install --user sphinx sphinx_rd_thme
    - name: Build the docs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sphinx-build -t html source build
        touch build/html/.nojekyll
    - name: Deploy the docs
      run: |
        mv build/html $HOME/docs
        cd $HOME/
        git init
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@github.com"
        git add .
        git commit -m "latest html output"
        git push -f https://${GITHUB_ACTOR}:${{secrets.ACCESS_TOKEN}}@github.com/intel/stacks.git HEAD:gh-pages
