name: Pull Request
on:
  # Trigger the workflow on pull request,
  # but only for the main branch
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - main
  # Also trigger on page_build, as well as release created events
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sudo apt-get install -y python3-setuptools
        pip3 install --user sphinx sphinx_rtd_theme
    - name: Build the docs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sphinx-build -t html source build